/*
 * Copyright 2026 The Forbric Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.forbric.kernel.boot;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.invoke.LambdaMetafactory;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.Method;
import java.util.function.Supplier;

import org.junit.jupiter.api.Test;

import net.forbric.kernel.classloading.DelegationPolicy;

/**
 * Pins the one thing {@link KernelGameLookup} exists for: the class it generates must yield a FULL-POWER lookup.
 *
 * <p>Forge's EventBus spins its listener lambdas with {@code LambdaMetafactory}, which rejects any caller whose
 * lookup lacks the MODULE bit — {@code LambdaConversionException: Invalid caller}. A boot-side
 * {@code MethodHandles.lookup()} teleported across the boot/game boundary loses that bit, so the kernel defines a
 * one-method helper INTO the game loader and asks it for a lookup instead.
 *
 * <p>The failure mode if that ever regressed is not a compile error and not an obvious crash: it is every
 * Forge-family mod's event listeners failing to bind, which surfaces as mods that load and then do nothing. So
 * this test does not inspect the generated bytecode — it defines the class, takes its lookup, and drives a real
 * {@code LambdaMetafactory} call through it, which is the exact operation that was failing.
 */
class KernelGameLookupTest {
	private static final String HELPER = "net.forbric.kernel.runtime.KernelGameLookupHelper";

	@Test
	void theGeneratedHelperYieldsALookupWithTheModuleBit() throws Exception {
		MethodHandles.Lookup lookup = lookupFromGeneratedHelper();

		assertNotNull(lookup, "the generated helper returned no lookup");
		assertNotEquals(0, lookup.lookupModes() & MethodHandles.Lookup.MODULE,
				"the lookup has no MODULE bit — LambdaMetafactory will reject every caller using it, and Forge's "
						+ "EventBus silently binds no listeners at all");
	}

	/** The operation that was actually failing: metafactory over that lookup must produce a working call site. */
	@Test
	void lambdaMetafactoryAcceptsThatLookupAsACaller() throws Throwable {
		MethodHandles.Lookup lookup = lookupFromGeneratedHelper();

		MethodHandle target = lookup.findStatic(lookup.lookupClass(), "lookup",
				MethodType.methodType(MethodHandles.Lookup.class));
		@SuppressWarnings("unchecked")
		Supplier<Object> made = (Supplier<Object>) LambdaMetafactory.metafactory(
				lookup, "get",
				MethodType.methodType(Supplier.class),
				MethodType.methodType(Object.class),
				target,
				MethodType.methodType(MethodHandles.Lookup.class)).getTarget().invoke();

		assertNotNull(made.get(), "the metafactory-built lambda produced nothing");
	}

	/** The helper must land on the GAME side, or it is minting a lookup for the wrong module. */
	@Test
	void theHelperNameIsPinnedGameSide() {
		assertTrue(DelegationPolicy.alwaysGame(HELPER),
				HELPER + " is not pinned game-side; a helper defined by the boot loader would hand back a lookup "
						+ "for the boot module, which is the thing this class exists to avoid");
	}

	/** It is generated, not shipped — nothing should be able to load it off the ordinary classpath. */
	@Test
	void theHelperIsNotOnTheOrdinaryClasspath() {
		assertEquals(false, canLoad(HELPER), "the helper is meant to be defined into the game loader at runtime");
	}

	// --- helpers ------------------------------------------------------------------------------------------------

	/** Ask the real KernelGameLookup for its generated bytes and define them here. */
	private static MethodHandles.Lookup lookupFromGeneratedHelper() throws Exception {
		Method generate = KernelGameLookup.class.getDeclaredMethod("generate");
		generate.setAccessible(true);
		byte[] bytes = (byte[]) generate.invoke(null);

		Class<?> helper = new ClassLoader(KernelGameLookupTest.class.getClassLoader()) {
			Class<?> define(byte[] b) {
				return defineClass(HELPER, b, 0, b.length);
			}
		}.define(bytes);

		return (MethodHandles.Lookup) helper.getMethod("lookup").invoke(null);
	}

	private static boolean canLoad(String name) {
		try {
			Class.forName(name, false, KernelGameLookupTest.class.getClassLoader());
			return true;
		} catch (ClassNotFoundException expected) {
			return false;
		}
	}
}
