package net.forbric.kernel.mixin;

import static org.junit.jupiter.api.Assertions.*;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.MethodNode;

/**
 * Re-derives {@code carrier-stubs.txt} — every merged-base method that is a pure delegating stub to a same-name overload
 * the CARRIER added (vanilla has the stub's signature and not the overload's) — and asserts the shipped table equals it.
 * MixinStubRebind moves a Fabric mod's injector only along a row here: where vanilla has both overloads itself, a mod
 * that chose the short one meant it.
 */
class CarrierStubCensusTest {
	private static final Path MERGED = Path.of(System.getenv().getOrDefault("FORBRIC_OLD", "../forbric-loader"), "run/merged-base/patched-mc-merged-26.2.jar");
	private static final Path VANILLA = Path.of(System.getProperty("user.home"), "Library/Application Support/minecraft/versions/26.2/26.2.jar");

	@Test void theShippedTableIsExactlyWhatTheArtifactsSay() throws Exception {
		Assumptions.assumeTrue(Files.isRegularFile(MERGED) && Files.isRegularFile(VANILLA), "merged base and vanilla jar required");
		Map<String, ClassNode> vanilla = read(VANILLA, true);
		TreeSet<String> rows = new TreeSet<>();
		try (ZipFile zip = new ZipFile(MERGED.toFile())) {
			for (ZipEntry entry : Collections.list(zip.entries())) {
				if (!entry.getName().endsWith(".class") || !entry.getName().startsWith("net/minecraft/")) continue;
				ClassNode merged = new ClassNode();
				new ClassReader(zip.getInputStream(entry).readAllBytes()).accept(merged, ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
				ClassNode original = vanilla.get(merged.name);
				if (original == null) continue;
				for (MethodNode stub : merged.methods) {
					// A compiler's generic bridge forwards to its typed overload too, and is no carrier's doing.
					if ((stub.access & (org.objectweb.asm.Opcodes.ACC_BRIDGE | org.objectweb.asm.Opcodes.ACC_SYNTHETIC)) != 0) continue;
					MixinStubRebind.Delegation delegation = MixinStubRebind.delegation(merged, stub);
					if (delegation == null) continue;
					if (!declares(original, stub.name, stub.desc) || declares(original, delegation.delegate().name, delegation.delegate().desc)) continue;
					rows.add(merged.name + "#" + stub.name + stub.desc + " -> " + delegation.delegate().desc);
				}
			}
		}
		List<String> shipped = new ArrayList<>();
		try (InputStream in = MixinStubRebind.class.getResourceAsStream(MixinStubRebind.TABLE)) {
			assertNotNull(in, MixinStubRebind.TABLE + " is missing");
			for (String line : new String(in.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
				if (!line.isBlank() && !line.startsWith("#")) shipped.add(line.trim());
			}
		}
		if (System.getenv("FORBRIC_WRITE_CARRIER_STUBS") != null) {
			Path out = Path.of("src/main/resources" + MixinStubRebind.TABLE);
			Files.writeString(out, "# Generated by CarrierStubCensusTest (FORBRIC_WRITE_CARRIER_STUBS=1): merged-base delegating stubs to a\n"
					+ "# same-name overload the carrier added. MixinStubRebind moves a Fabric mod's injector only along these rows.\n"
					+ String.join("\n", rows) + "\n");
		}
		assertEquals(rows, new TreeSet<>(shipped), "carrier-stubs.txt must equal what the staged merged base and vanilla say; "
				+ "regenerate with FORBRIC_WRITE_CARRIER_STUBS=1 after a base rebuild");
	}

	private static boolean declares(ClassNode node, String name, String desc) {
		for (MethodNode m : node.methods) if (m.name.equals(name) && m.desc.equals(desc)) return true;
		return false;
	}

	private static Map<String, ClassNode> read(Path jar, boolean skipCode) throws Exception {
		Map<String, ClassNode> out = new HashMap<>();
		try (ZipFile zip = new ZipFile(jar.toFile())) {
			for (ZipEntry entry : Collections.list(zip.entries())) {
				if (!entry.getName().endsWith(".class") || !entry.getName().startsWith("net/minecraft/")) continue;
				ClassNode node = new ClassNode();
				new ClassReader(zip.getInputStream(entry).readAllBytes()).accept(node, skipCode ? ClassReader.SKIP_CODE : 0);
				out.put(node.name, node);
			}
		}
		return out;
	}
}
